/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultima6;

import com.badlogic.gdx.graphics.Color;
import java.awt.Component;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.io.FileInputStream;
import java.nio.ByteBuffer;
import java.util.Iterator;
import java.util.zip.GZIPInputStream;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.CharUtils;
import ultima6.Conversations.OutputStream;

/**
 *
 * @author Paul
 */
public class ConverseUI extends javax.swing.JFrame {

    /**
     * Creates new form ConverseUI
     */
    public ConverseUI() {
        initComponents();

        party = new Party();

        avatar = new Player(1, "avatar");
        party.add(avatar);

        player2 = new Player(2, "dupre");
        party.add(player2);

        GZIPInputStream is;
        ByteBuffer bba = null;
        try {
            is = new GZIPInputStream(new FileInputStream("src\\main\\resources\\data\\conversations"));

            byte[] tmp = IOUtils.toByteArray(is);
            is.close();

            bba = ByteBuffer.wrap(tmp);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        Conversations convs = new Conversations();

        while (bba.position() < bba.limit()) {
            short len = bba.getShort();
            byte[] data = new byte[len];
            bba.get(data);
            StringBuilder sb = new StringBuilder();
            byte b = 0;
            for (int i = 2; i < 20; i++) {
                b = data[i];
                if (b == (byte) 0xf1) {
                    break;
                }
                sb.append((char) b);
            }
            convs.put(data[1] & 0xff, sb.toString(), data);
        }

        DefaultListModel<Conversations.Conversation> model = new DefaultListModel<>();
        ListCellRenderer cellRenderer = new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (c instanceof JLabel) {
                    JLabel label = (JLabel) c;
                    Conversations.Conversation conv = (Conversations.Conversation) value;
                    label.setText(conv.getName());
                }
                return c;
            }
        };

        ListSelectionListener selectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    JList source = (JList) e.getSource();

                    selected = (Conversations.Conversation) source.getSelectedValue();

                    selected.init(avatar, party);

                    DefaultListModel<String> cmodel = (DefaultListModel) conversation.getModel();
                    cmodel.clear();

                    ByteBuffer bb = selected.data();
                    debugTA.setText(debugOutput(bb));

                }
            }

        };

        names.setModel(model);
        names.setCellRenderer(cellRenderer);
        names.addListSelectionListener(selectionListener);

        Iterator<Conversations.Conversation> iter = convs.iter();
        while (iter.hasNext()) {
            Conversations.Conversation conv = iter.next();
            model.addElement(conv);
        }

        DefaultListModel<String> cmodel = new DefaultListModel<>();
        conversation.setModel(cmodel);

        convSP.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {
            public void adjustmentValueChanged(AdjustmentEvent e) {
                e.getAdjustable().setValue(e.getAdjustable().getMaximum());
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namesSP = new javax.swing.JScrollPane();
        names = new javax.swing.JList<>();
        convSP = new javax.swing.JScrollPane();
        conversation = new javax.swing.JList<>();
        input = new javax.swing.JTextField();
        debugSP = new javax.swing.JScrollPane();
        debugTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namesSP.setViewportView(names);

        convSP.setViewportView(conversation);

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        debugTA.setColumns(20);
        debugTA.setRows(5);
        debugSP.setViewportView(debugTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(debugSP)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namesSP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input)
                            .addComponent(convSP, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(convSP, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(namesSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debugSP, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        String in = input.getText();
        input.setText("");
        selected.process(avatar, party, in, output);
    }//GEN-LAST:event_inputActionPerformed

    private static String debugOutput(ByteBuffer bb) {
        bb.rewind();
        StringBuffer sb = new StringBuffer();
        while (bb.position() < bb.limit()) {
            U6OP op = U6OP.get(bb);
            if (op != null) {

                bb.get();

                if (op == U6OP.IF || op == U6OP.ASK || op == U6OP.DECL || op == U6OP.KEYWORDS || op == U6OP.ASKC || op == U6OP.ENDANSWERS) {
                    sb.append("" + bb.position() + "\n");
                }

                if (op == U6OP.JUMP) {
                    sb.append(String.format("[%s to %d]", op, bb.getInt()));
                } else {
                    sb.append(String.format("[%s]", op));
                }

                if (op == U6OP.ENDANSWERS || op == U6OP.ENDIF || op == U6OP.ASK) {
                    sb.append("\n");
                }

            } else {
                boolean ascii = CharUtils.isAsciiPrintable((char) bb.get(bb.position()));
                sb.append(ascii ? (char) bb.get(bb.position()) : String.format("[%02X]", bb.get(bb.position())));
                bb.get();
            }
        }
        
        return sb.toString();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverseUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane convSP;
    private javax.swing.JList<String> conversation;
    private javax.swing.JScrollPane debugSP;
    private javax.swing.JTextArea debugTA;
    private javax.swing.JTextField input;
    private javax.swing.JList<Conversations.Conversation> names;
    private javax.swing.JScrollPane namesSP;
    // End of variables declaration//GEN-END:variables

    private Party party;
    private Player avatar;
    private Player player2;
    Conversations.Conversation selected;

    private final OutputStream output = new OutputStream() {
        @Override
        public void print(String text, Color color) {
            DefaultListModel<String> cmodel = (DefaultListModel) conversation.getModel();
            cmodel.addElement(text);
        }

        @Override
        public void close() {
        }

        @Override
        public void setPortrait(int npc) {
        }
    };

}
